# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
##### Setting Build No #####
name: $(BuildDefinitionName)$(Rev:.r)

trigger:
- main

##### Setting Stages #####
stages:
- stage: 'PreBuildStage'
  displayName: 'Setting Up Java Environment for Build'
  jobs:
    - job: 'PreBuildProcess'
      displayName: 'Java Environment Setup'
      pool: 
        name: 'ORSAgentPool'      
      steps:
        - script: echo Agent Configuration!
          displayName: 'Setting up Agent Configuration'
         
        - task: JavaToolInstaller@0
          displayName: Java Tool Installer
          inputs:
            versionSpec: '8'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'LocalDirectory'
            jdkFile: 'C:\Software\jdk-16.0.1_windows-x64_bin.zip'
            jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk16.0.1'
            cleanDestinationDirectory: false
    
- stage: 'BuildStage'
  displayName: 'Java Build'
  jobs:
    - job: 'BuildProcess'
      displayName: 'Java Build Process'
      pool: 
        name: 'ORSAgentPool'      
      steps:
        - script: echo Build Configuration!
          displayName: 'Build Java Application'