# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
##### Setting Build No #####
name: $(BuildDefinitionName)$(Rev:.r)

trigger:
- main

##### Setting Stages #####
stages:
- stage: 'BuildStage'
  displayName: 'Setting Up Java Environment for Build'
  jobs:
    - job: 'BuildProcess'
      displayName: 'Build Process Job'
      pool:
        #vmImage: 'windows-latest'        
        name: 'ORSAgentPool'
        demands:
        - agent.name -equals 'ORSBuildAgent'
      steps:
        - script: echo Hello, world!
          displayName: 'Setting up Agent Configuration'
       