# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
##### Setting Build No #####
name: $(BuildDefinitionName)$(Rev:.r)

trigger:
- main
#parameters:
  #- name: variablegroup1
    #default: ORSBuildVariable
    
##### Setting Stages #####
stages:
- stage: 'BuildStage'
  displayName: 'ORS Application Build'
  jobs:
    - job: 'BuildProcess'
      displayName: 'ORS Build Process'
      pool: 
        name: 'ORSAgentPool'      
        demands:
         - agent.name -equals ORSBuildAgent
      steps:         
        - task: JavaToolInstaller@0
          displayName: Java Tool Installer
          inputs:
            versionSpec: '8'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'LocalDirectory'
            jdkFile: $(jdkFilePath)
            jdkDestinationDirectory: $(jdkDestinationPath)
            cleanDestinationDirectory: false

        - task: Maven@3
          displayName: 'Maven Build'
          inputs:
            mavenPomFile: 'pom.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            publishJUnitResults: false
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
            #goals: 'integration-test -DskipIntegrationTests=false -Dmaven.test.failure.ignore=true'
       
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: $(Build.DefinitionName).$(Build.BuildId).zip'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            #ArtifactName: '$(Build.DefinitionName).$(Build.BuildId).zip'
            ArtifactName: '$(Build.BuildNumber).zip'
            artifactType:  container
        - task: PowerShell@2
          inputs:
            filePath: '$(Build.SourcesDirectory)\BuildScripts\SOM.DTMB.UpdateArtifactVersionNo.ps1'
